[book]
authors = ["KazumichiINOUE"]
language = "jp"
multilingual = false
src = "src"
title = "irlaben — IRLab. Essential Notes —"

[output.html]
mathjax-support = true
additional-css = ["theme/custom.css"]
default-theme = "rust"

#[output.pdf]

[output.html.playground]
runnable = true
editable = true     # true にするとコードの編集が可能になる
copyable = true     # コピーボタンを表示
line-numbers = true # 行番号を表示
